---
collections:
  - name: https://github.com/k3s-io/k3s-ansible.git
    type: git
    version: 1.2.2 # git version tag

    # Used for ArgoCD installation
  - name: kubernetes.core
    version: 6.5.0
