argocd:
  # Values for the upstream argo-cd Helm chart.
  configs:
    params:
      # Keep TLS enabled on the Argo CD API server.
      server.insecure: true # will use cert

  server:
    ingress:
      enabled: true
      ingressClassName: traefik
      path: /
      hostname: argocd.homelab
      annotations:
        cert-manager.io/cluster-issuer: selfsigned
      labels: {}
      tls: false
      extraTls:
        - secretName: argocd-tls
          hosts:
            - argocd.homelab

projects:
  - name: gitops-infra
    description: gitops-infra ArgoCD project to manage git folder - gitops/infra
    sourceRepos:
      - https://github.com/MooseStack/kubernetes_k3s_cluster.git
    destinations:
      - namespace: "*"
        server: https://kubernetes.default.svc
    namespaceResourceWhitelist:
      - group: "*"
        kind: "*"
    clusterResourceWhitelist:
      - group: "*"
        kind: "*"
  - name: gitops-apps
    description: Argo CD project for gitops/apps/projectName that dont specify a project
    sourceRepos:
      - https://github.com/MooseStack/kubernetes_k3s_cluster.git
    destinations:
      - namespace: "*"
        server: https://kubernetes.default.svc
    namespaceResourceWhitelist:
      - group: "*"
        kind: "*"
    clusterResourceWhitelist:
      - group: ""
        kind: Namespace
  - name: tailscale
    description: Argo CD project for tailscale application
    sourceRepos:
      - https://github.com/MooseStack/tailscale_helm.git
      - https://github.com/MooseStack/kubernetes_k3s_cluster.git
    destinations:
      - namespace: tailscale
        server: https://kubernetes.default.svc
    clusterResourceWhitelist:
      - group: ""
        kind: Namespace
        name: "tailscale"
    namespaceResourceWhitelist:
      - group: apps
        kind: Deployment
      - group: rbac.authorization.k8s.io
        kind: Role
      - group: rbac.authorization.k8s.io
        kind: RoleBinding
      - group: ""
        kind: ServiceAccount
      - group: ""
        kind: Secret
  - name: immich
    description: Argo CD project for Immich
    sourceRepos:
      - https://github.com/MooseStack/kubernetes_k3s_cluster.git
      - ghcr.io/immich-app/immich-charts
    destinations:
      - namespace: immich
        server: https://kubernetes.default.svc
    clusterResourceWhitelist:
      - group: ""
        kind: Namespace
        name: "immich"
    namespaceResourceWhitelist:
      - group: "*"
        kind: "*"

repositories:
  - name: repo-1406131573
    project: gitops-infra
    url: https://github.com/MooseStack/kubernetes_k3s_cluster.git
    
  - name: tailscalehelm
    project: tailscale
    url: https://github.com/MooseStack/tailscale_helm.git

  - name: immichcharts
    project: immich
    type: helm
    enableOCI: true
    url: ghcr.io/immich-app/immich-charts
