projects:

  - name: tailscale
    description: Argo CD project for tailscale application
    sourceRepos:
      - https://github.com/MooseStack/tailscale_helm.git
      - https://github.com/MooseStack/kubernetes_k3s_cluster.git
    destinations:
      - namespace: tailscale
        server: https://kubernetes.default.svc
    namespaceResourceWhitelist:
      - group: "*"
        kind: "*"

repositories:
  - name: kubernetesk3scluster
    url: https://github.com/MooseStack/kubernetes_k3s_cluster.git
    
  - name: tailscalehelm
    project: tailscale
    url: https://github.com/MooseStack/tailscale_helm.git
